import type { TimerConfig } from "../lib/timer"

export interface Theme {
  name: string
  description: string
  config: Partial<TimerConfig>
}

export const themes: Theme[] = [
  {
    name: "Default",
    description: "Clean and modern design",
    config: {
      text: "⚡ Limited-time offer! Sale ends in",
      textPosition: "top",
      buttonText: "Shop now",
      buttonPosition: "bottom",
      showButton: true,
      timerStyle: "rounded",
      backgroundColor: "#f8fafc",
      textColor: "#1e293b",
      timerColor: "#3b82f6",
      timerTextColor: "#ffffff",
      buttonColor: "#1f2937",
      buttonTextColor: "#ffffff",
      buttonHoverColor: "#111827",
      showLabels: true,
      showTimerShadow: true,
      showButtonShadow: true,
      customTextCSS: "",
      customButtonCSS: "",
      customTimerCSS: "",
    },
  },
  {
    name: "Black Friday",
    description: "Bold black and yellow theme",
    config: {
      text: "Black Friday Sale up to 50% OFF",
      textPosition: "top",
      buttonText: "Shop now",
      buttonPosition: "bottom",
      showButton: true,
      timerStyle: "rounded",
      backgroundColor: "#000000",
      textColor: "#fbbf24",
      timerColor: "#fbbf24",
      timerTextColor: "#000000",
      buttonColor: "#fbbf24",
      buttonTextColor: "#000000",
      buttonHoverColor: "#f59e0b",
      showLabels: true,
      showTimerShadow: false,
      showButtonShadow: false,
      textFont: "font-sans",
      buttonFont: "font-sans",
      customTextCSS: "font-size: 32px; font-weight: 700; text-transform: uppercase;",
      customButtonCSS: "font-weight: 600; padding: 16px 32px; font-size: 18px;",
      customTimerCSS: "font-size: 48px; font-weight: 700; padding: 16px 20px;",
    },
  },
  {
    name: "Wedding",
    description: "Romantic pink and red theme",
    config: {
      text: "Our Wedding Countdown 💍\nDays until we become Mr & Mrs 👰🤵",
      textPosition: "top",
      buttonText: "Shop now",
      buttonPosition: "bottom",
      showButton: true,
      timerStyle: "rounded",
      backgroundColor: "#ffe4e6",
      textColor: "#e11d48",
      timerColor: "#e11d48",
      timerTextColor: "#ffffff",
      buttonColor: "#e11d48",
      buttonTextColor: "#ffffff",
      buttonHoverColor: "#be123c",
      showLabels: true,
      showTimerShadow: true,
      showButtonShadow: true,
      textFont: "font-sans",
      buttonFont: "font-sans",
      customTextCSS: "font-size: 36px; font-weight: 700; text-align: center; line-height: 1.3;",
      customButtonCSS: "font-weight: 600; padding: 16px 48px; font-size: 18px; border-radius: 12px;",
      customTimerCSS: "font-size: 56px; font-weight: 700; padding: 20px 24px; border-radius: 16px;",
    },
  },
  {
    name: "Special Offer",
    description: "Dark theme with orange accent",
    config: {
      text: "Special Offer 30% OFF 🔥\nYour coupon: #SALECOUPON",
      textPosition: "top",
      buttonText: "Shop now",
      buttonPosition: "bottom",
      showButton: true,
      timerStyle: "rounded",
      backgroundColor: "#000000",
      textColor: "#ffffff",
      timerColor: "#fbbf24",
      timerTextColor: "#000000",
      buttonColor: "#f97316",
      buttonTextColor: "#ffffff",
      buttonHoverColor: "#ea580c",
      showLabels: true,
      showTimerShadow: false,
      showButtonShadow: false,
      textFont: "font-sans",
      buttonFont: "font-sans",
      customTextCSS: "font-size: 28px; font-weight: 700; line-height: 1.4;",
      customButtonCSS: "font-weight: 600; padding: 14px 32px; font-size: 18px; border-radius: 8px;",
      customTimerCSS: "font-size: 40px; font-weight: 700; padding: 12px 16px; border-radius: 8px;",
    },
  },
  {
    name: "Christmas",
    description: "Festive red and green theme",
    config: {
      text: "🎄 Christmas Sale! 🎅\nHoliday Deals End Soon",
      textPosition: "top",
      buttonText: "Shop Gifts",
      buttonPosition: "bottom",
      showButton: true,
      timerStyle: "rounded",
      backgroundColor: "#7f1d1d",
      textColor: "#fef3c7",
      timerColor: "#15803d",
      timerTextColor: "#ffffff",
      buttonColor: "#dc2626",
      buttonTextColor: "#ffffff",
      buttonHoverColor: "#b91c1c",
      showLabels: true,
      showTimerShadow: true,
      showButtonShadow: true,
      textFont: "font-sans",
      buttonFont: "font-sans",
      customTextCSS: "font-size: 32px; font-weight: 700; text-align: center; line-height: 1.4;",
      customButtonCSS: "font-weight: 600; padding: 16px 40px; font-size: 18px; border-radius: 12px;",
      customTimerCSS: "font-size: 48px; font-weight: 700; padding: 18px 22px; border-radius: 12px;",
    },
  },
  {
    name: "Diwali",
    description: "Vibrant orange and gold theme",
    config: {
      text: "🪔 Diwali Festival Sale! ✨\nCelebrate with Amazing Offers",
      textPosition: "top",
      buttonText: "Shop Now",
      buttonPosition: "bottom",
      showButton: true,
      timerStyle: "rounded",
      backgroundColor: "#7c2d12",
      textColor: "#fbbf24",
      timerColor: "#f97316",
      timerTextColor: "#ffffff",
      buttonColor: "#fbbf24",
      buttonTextColor: "#7c2d12",
      buttonHoverColor: "#f59e0b",
      showLabels: true,
      showTimerShadow: true,
      showButtonShadow: true,
      textFont: "font-sans",
      buttonFont: "font-sans",
      customTextCSS: "font-size: 34px; font-weight: 700; text-align: center; line-height: 1.4;",
      customButtonCSS: "font-weight: 700; padding: 16px 40px; font-size: 18px; border-radius: 12px;",
      customTimerCSS: "font-size: 50px; font-weight: 700; padding: 18px 22px; border-radius: 12px;",
    },
  },
  {
    name: "Holi",
    description: "Colorful festival of colors theme",
    config: {
      text: "🎨 Holi Festival Sale! 🌈\nColorful Deals Await",
      textPosition: "top",
      buttonText: "Celebrate",
      buttonPosition: "bottom",
      showButton: true,
      timerStyle: "rounded",
      backgroundColor: "#fef3c7",
      textColor: "#ec4899",
      timerColor: "#8b5cf6",
      timerTextColor: "#ffffff",
      buttonColor: "#10b981",
      buttonTextColor: "#ffffff",
      buttonHoverColor: "#059669",
      showLabels: true,
      showTimerShadow: true,
      showButtonShadow: true,
      textFont: "font-sans",
      buttonFont: "font-sans",
      customTextCSS: "font-size: 36px; font-weight: 700; text-align: center; line-height: 1.4;",
      customButtonCSS: "font-weight: 600; padding: 16px 40px; font-size: 18px; border-radius: 16px;",
      customTimerCSS: "font-size: 48px; font-weight: 700; padding: 18px 22px; border-radius: 16px;",
    },
  },
  {
    name: "Easter",
    description: "Soft pastel spring theme",
    config: {
      text: "🐰 Easter Sale! 🥚\nSpring Savings End Soon",
      textPosition: "top",
      buttonText: "Shop Easter",
      buttonPosition: "bottom",
      showButton: true,
      timerStyle: "rounded",
      backgroundColor: "#fce7f3",
      textColor: "#a855f7",
      timerColor: "#ec4899",
      timerTextColor: "#ffffff",
      buttonColor: "#a855f7",
      buttonTextColor: "#ffffff",
      buttonHoverColor: "#9333ea",
      showLabels: true,
      showTimerShadow: true,
      showButtonShadow: true,
      textFont: "font-sans",
      buttonFont: "font-sans",
      customTextCSS: "font-size: 32px; font-weight: 700; text-align: center; line-height: 1.4;",
      customButtonCSS: "font-weight: 600; padding: 16px 40px; font-size: 18px; border-radius: 20px;",
      customTimerCSS: "font-size: 48px; font-weight: 700; padding: 18px 22px; border-radius: 16px;",
    },
  },
  {
    name: "Eid",
    description: "Elegant green and gold theme",
    config: {
      text: "🌙 Eid Mubarak! ⭐\nSpecial Eid Offers",
      textPosition: "top",
      buttonText: "Shop Now",
      buttonPosition: "bottom",
      showButton: true,
      timerStyle: "rounded",
      backgroundColor: "#064e3b",
      textColor: "#fbbf24",
      timerColor: "#10b981",
      timerTextColor: "#ffffff",
      buttonColor: "#fbbf24",
      buttonTextColor: "#064e3b",
      buttonHoverColor: "#f59e0b",
      showLabels: true,
      showTimerShadow: true,
      showButtonShadow: true,
      textFont: "font-sans",
      buttonFont: "font-sans",
      customTextCSS: "font-size: 34px; font-weight: 700; text-align: center; line-height: 1.4;",
      customButtonCSS: "font-weight: 700; padding: 16px 40px; font-size: 18px; border-radius: 12px;",
      customTimerCSS: "font-size: 50px; font-weight: 700; padding: 18px 22px; border-radius: 12px;",
    },
  },
]
